### PR TITLE
Fix: Make different accounts can see different projects

### PR DESCRIPTION
**Pull request by jn2657**
# Description

- Add `getMemberId` function to return memberId by giving username.

### CODE REVIEW

**Review by VincentETN — COMMENTED** [review]
Username isn't unique. 除非把 username 當成 account。

**Comment by jn2657** [comment]
Username 是 unique, 請參照 package `entity` -> class `member` -> column `username`

**Comment by Xanonymous-GitHub** [comment]
@VincentETN You can follow this sql scripts for https://github.com/SE-8-2021/backend/pull/37#issuecomment-1007374161 .

```sql
DO
$do$
    BEGIN
        IF EXISTS(SELECT FROM pg_database WHERE datname = 'PVS') THEN
            RAISE NOTICE 'Database already exists';
        ELSE
            PERFORM dblink_exec('dbname=' || current_database()
                , 'CREATE DATABASE PVS');
        END IF;
    END
$do$;

CREATE TABLE IF NOT EXISTS member
(
    member_id BIGINT NOT NULL,
    username  VARCHAR(255) UNIQUE,
    password  VARCHAR(255),
    PRIMARY KEY (member_id)
);

CREATE TABLE IF NOT EXISTS role
(
    role_id BIGINT NOT NULL,
    name    VARCHAR(255) UNIQUE,
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS member_role
(
    member_id BIGINT NOT NULL,
    role_id   BIGINT NOT NULL,
    PRIMARY KEY (member_id, role_id),
    FOREIGN KEY (member_id) REFERENCES member (member_id),
    FOREIGN KEY (role_id) REFERENCES role (role_id)
);
```

**Review by VincentETN — DISMISSED** [review]

**Comment by VincentETN** [comment]
那沒問題。

**Review by VincentETN — APPROVED** [review]

**Review by Xanonymous-GitHub — APPROVED** [review]

**Review by hellenGUAN — APPROVED** [review]

**Pull request merged**
